# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smv < Formula
  desc ""
  homepage "https://github.com/vague2k/smv"
  version "0.1.0"
  license "MIT"

  depends_on "ffmpeg"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vague2k/smv/releases/download/v0.1.0/smv_0.1.0_darwin_arm64.tar.gz"
      sha256 "cabccc9ffd7f795b9a4d6e8cb8eac1b8c829be3bbcd8e98b55334314e48b7bc5"

      def install
        bin.install "smv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vague2k/smv/releases/download/v0.1.0/smv_0.1.0_darwin_amd64.tar.gz"
      sha256 "94e4c4423f1a9101cc08484ed6a8f8d6fd310f6b57304b79ae9732728a341b32"

      def install
        bin.install "smv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/vague2k/smv/releases/download/v0.1.0/smv_0.1.0_linux_armv6.tar.gz"
      sha256 "bdffd45789846bc4b1500f0c50857dd853edfc5a54f9e39a3d66315abedb37d4"

      def install
        bin.install "smv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vague2k/smv/releases/download/v0.1.0/smv_0.1.0_linux_arm64.tar.gz"
      sha256 "374984f23a5cac343e16ce0a7eec381e1cff1eec40cea8d6bc79f0ea06ff4833"

      def install
        bin.install "smv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vague2k/smv/releases/download/v0.1.0/smv_0.1.0_linux_amd64.tar.gz"
      sha256 "1db792ae7be94c930f6d5b486a82f0915746a65568084273e420f425873a70d4"

      def install
        bin.install "smv"
      end
    end
  end
end
